name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      # Naviguer dans le sous-dossier `frontend`
      - name: Change directory to /frontend
        working-directory: ./frontend # Assure-toi que le chemin est correct
        run: pwd # Cette commande affiche le répertoire actuel dans les logs, utile pour vérifier

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Installer les dépendances dans le dossier `frontend`
      - name: Install dependencies
        working-directory: ./frontend # Assure-toi de toujours pointer vers le bon dossier
        run: npm ci

      # Build le projet dans `frontend`
      - name: Build project
        working-directory: ./frontend
        run: npm run build --if-present

      # Tester le projet (optionnel selon tes besoins)
      - name: Run tests
        working-directory: ./frontend
        run: npm test

      # Déployer avec gh-pages
      - name: Deploy with gh-pages
        working-directory: ./frontend # Toujours pointer vers `frontend`
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
